### ISSUE TITLE
Dispatcher branch build crashes when despawning bullets

### ISSUE THREAD

**Issue by LukeLinkwalker** [NotHolst/CBSE-G7#3]
Because of the change from ArrayList to CopyOnWriteArrayList a UnsupportedOperationException is now thrown whenever a bullet is despawned. A possible solution would be to finally implement the dispose event so that bullets can dispose of 'old' bullets at the end of the game loop as suggested on [stackoverflow](http://stackoverflow.com/a/5612505).

**Comment by LukeLinkwalker** [comment]
java.lang.UnsupportedOperationException
        at java.util.concurrent.CopyOnWriteArrayList$COWIterator.remove(CopyOnWriteArrayList.java:1176)
	at dk.gruppe7.bullet.BulletSystem.process(BulletSystem.java:91)
	at dk.gruppe7.core.Game.update(Game.java:122)
	at dk.gruppe7.core.Game.render(Game.java:112)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
[catch] at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

**Comment by LukeLinkwalker** [comment]
A solution to the issue has been found and has been described in the commit referenced above.
